---

sw1:
    hostname: "192.168.68.117"
    groups:
        - nexus
    data:
        loopback: "1.1.1.1"

sw2:
    hostname: "192.168.68.115"
    groups:
        - ios
    data:
        loopback: "2.2.2.2"

    



